# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Tiago Evangelista
description: Estudante de Medicina Veterinária.
author: Tasso Evangelista
email: tiagoevanp@hotmail.com
